name: calagopus

services:
  web:
    image: ghcr.io/calagopus/panel:1.2.4@sha256:be6f9e0414fbc0e3d4fd192557f4e8b29a73794e017a375a5b3325e5d850484f
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - -c
      - |
        [ -s /var/lib/calagopus/.encryption-key ] || (umask 077; head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > /var/lib/calagopus/.encryption-key)
        export APP_ENCRYPTION_KEY="$(cat /var/lib/calagopus/.encryption-key)"
        exec /usr/bin/panel-rs "$$@"
      - panel-rs
    environment:
      - TZ=$TZ
      - REDIS_URL=redis://cache
      - DATABASE_URL=postgresql://panel:panel@db/panel
      - DATABASE_MIGRATE=true
      - PORT=8000
      - APP_DEBUG=false
      - APP_LOG_DIRECTORY=/var/log/calagopus
      - APP_PRIMARY=true
      - APP_ENABLE_WINGS_PROXY=true
      - APP_USE_DECRYPTION_CACHE=true
      - APP_USE_INTERNAL_CACHE=true
    ports:
      - target: "8000"
        published: "8000"
    volumes:
      - /DATA/AppData/$AppID/data:/var/lib/calagopus
      - /DATA/AppData/$AppID/logs:/var/log/calagopus
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      - calagopus
  db:
    image: ghcr.io/calagopus/pgautoupgrade:18-alpine@sha256:a61b9ca2a3d85f71c9091a69883984c708d613572e98b99a38ce47537ce6f3c5
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - POSTGRES_USER=panel
      - POSTGRES_PASSWORD=panel
      - POSTGRES_DB=panel
      - PGDATA=/data
    volumes:
      - /DATA/AppData/$AppID/postgres:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U panel -d panel"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - calagopus

  cache:
    image: ghcr.io/calagopus/valkey:latest@sha256:43d8e6e6fa52d48398cb31ae95783d59298b047985e71f0b10c04fbdb7f26dcd
    restart: unless-stopped
    command: --protected-mode no --save 60 1
    environment:
      TZ: $TZ
    volumes:
      - /DATA/AppData/$AppID/cache:/data
    networks:
      - calagopus

networks:
  calagopus:
    driver: bridge

x-casaos:
  id: com.calagopus.panel
  main: web
  version: "1.2.4"
  index: /
  scheme: http
  port_map: "8000"
  icon: https://calagopus.github.io/zimaos-appstore/apps/com.calagopus.panel/assets/icon.svg
  title:
    en_US: Calagopus
